[project]
name = "shed_pi"
version = "0.0.1"
authors = [
  { name="Aiky30" },
]
description = "Shed Pi"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "TODO"
"Bug Tracker" = "TODO"