# Generated by Django 5.0.1 on 2024-04-19 18:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shedpi_hub_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicemodulereading",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
