name: Test
on:
  push:
    branches-ignore:
      - "release/**"

jobs:
  build-and-test:
    name: Test code
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
